name: Go package

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o easybackup_linux_amd64

      - name: Upload Build results
        uses: actions/upload-artifact@v3
        with:
          name: easybackup_linux_amd64
          path: easybackup_linux_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: easybackup_linux_amd64
